# See http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci

language: cpp
compiler: g++
dist:     trusty
addons:
  apt:
    sources:
    - sourceline: 'ppa:mhier/libboost-latest'
    - ubuntu-toolchain-r-test
    #- boost-latest
    packages:
    - gcc-9
    - g++-9
    - boost1.70
    #- cmake
    #- cmake-data
    - libxslt1.1
    - python-lxml
    - doxygen
  env:
    - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-tarball

before_script:
  - |
    echo "PKG_ROOT_DIR=/usr/local"                               > .cmake-args.${HOSTNAME}
    echo "WITH_THRIFT=OFF"                                      >> .cmake-args.${HOSTNAME}
#    echo "ENV:BOOST_ROOT=${BOOST_ROOT}"                         >> .cmake-args.${HOSTNAME}
    echo "WITH_ENUM_SERIALIZATION=ON"                           >> .cmake-args.${HOSTNAME}
  - g++ --version

script:
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}      # Go back to the root of the project and bootstrap
  - make bootstrap toolchain=clang generator=make build=debug
  - make jobs=$(nproc)

branches:
  only: master
