# See http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci

language: cpp
compiler: g++
dist:     trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    #- boost-latest
    packages:
    - gcc-8
    - g++-8
    #- libboost1.65-all-dev
    #- cmake
    #- cmake-data
    - libxslt1.1
    - python-lxml
    - doxygen
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-tarball

before_install:
  - export CC=gcc-8
  - export CXX=g++-8
  - g++ --version | head -1
  - lsb_release -a && uname -a
  - nproc
  #- sudo apt-get -y install cmake
  #- sudo apt-get update -qq
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Build Boost
  - pushd .
  - mkdir -p deps
  - cd deps
  - CMAKE_URL="http://www.cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"
  - mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${PWD}/cmake/bin:${PATH}
  - which cmake
  - cmake --version
  - INSTALL=${PWD}/boost-install
  - mkdir -p ${INSTALL}
  - |
    if [ ! -f "boost-tarball/boost.tgz" ]; then
      rm -rf boost_* boost-tarball
      TARBALL=boost_1_72_0.tar.gz
      wget -q http://downloads.sourceforge.net/boost/${TARBALL}
      tar zxf ${TARBALL}
      cd ${TARBALL%.tar.gz}
      pwd
      chmod +x bootstrap.sh
      #./bootstrap.sh --prefix="${INSTALL}" --with-libraries="program_options,filesystem,system,chrono,date_time,unit_test_framework"
      ./bootstrap.sh --prefix="${INSTALL}"
      ./b2 headers
      #./b2 toolset=gcc-8 cxxflags="-std=c++14" variant=release link=static --with-filesystem --with-system --with-regex --with-date_time --with-chrono --with-program_options --with-thread --with-unit_test_framework --with-timer install -d1
      ./b2 toolset=gcc-8 cxxflags="-std=c++14" variant=release link=shared install -d1
      mkdir -p ../boost-tarball
      cd ${INSTALL}
      tar zcf ../boost-tarball/boost.tgz .
    else
      echo "Using cached BOOST from ${TRAVIS_BUILD_DIR}/deps/boost-tarball/boost.tgz"
      cd ${INSTALL}
      tar zxf ../boost-tarball/boost.tgz
    fi
  - export BOOST_ROOT="${INSTALL}"
  - ls -l ${BOOST_ROOT}/lib
  - popd  

before_script:
  - |
    echo "PKG_ROOT_DIR=/usr/local"                               > .cmake-args.${HOSTNAME}
    echo "WITH_THRIFT=OFF"                                      >> .cmake-args.${HOSTNAME}
    echo "ENV:BOOST_ROOT=${BOOST_ROOT}"                         >> .cmake-args.${HOSTNAME}
    echo "WITH_ENUM_SERIALIZATION=ON"                           >> .cmake-args.${HOSTNAME}
  - g++ --version

script:
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}      # Go back to the root of the project and bootstrap
  - make bootstrap toolchain=clang generator=make build=debug
  - make jobs=$(nproc)

branches:
  only: master
